import React, { useState, useEffect, useCallback, useRef } from 'react';
import { wallpaperCategoriesCatalog as catalog } from '../data/wallpapers';
import { SliderField } from './controls';
import { Sparkles, Trash2 } from 'lucide-react';
import { ResetIcon } from '../ui/icons.jsx';
import { renderBackgroundToCanvas } from '../../utils/image/canvasBackgroundFx';
import { extractPaletteFromDataUrl } from '../../utils/color/colorPalette';
import { useI18n } from './I18nContext';
import { baseOptions } from '../../utils/core/editorOptions';
import {
  isSameWallpaperSelection,
  isSameGradientSelection,
  isSameBlobGradientSelection,
  toggleWallpaperOff,
  toggleGradientOff,
  toggleBlobGradientOff,
} from '../../utils/image/backgroundToggle';
import { isAbsoluteFilePath, toSafeUrl } from '../../utils/platform/pathHelpers';

const FALLBACK_PIXEL_PNG =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==';

export const defaultLocalCategories = catalog;

const deriveThumbnail = (path, overrides = {}) => {
  if (!path) return null;
  if (path.includes('/thumbs/')) return path;
  if (path.startsWith('/backgrounds/')) {
    return path.replace('/backgrounds/', '/backgrounds/thumbs/');
  }
  return overrides[path] || path;
};

const resolveRenderableUrl = (maybeUrl, filePath = null) => {
  const url = (typeof maybeUrl === 'string') ? maybeUrl : null;
  const fp = (typeof filePath === 'string' && filePath) ? filePath : null;

  // If we have an absolute file path, never hand it directly to the WebView.
  // Convert it to an asset URL when possible; otherwise return null so callers
  // can use a placeholder until the bridge is ready.
  const absolute = fp || (url && isAbsoluteFilePath(url) ? url : null);
  if (absolute) {
    if (typeof window !== 'undefined' && window?.tauriAPI?.filePathToAssetUrl) {
      try {
        return toSafeUrl(window.tauriAPI.filePathToAssetUrl(absolute));
      } catch {
        return null;
      }
    }
    return null;
  }

  return toSafeUrl(url);
};

const normalizeCategory = (category) => ({
  ...category,
  images: (category.images || []).map((image) => {
    const base = image.path || image.fullSizePath || image;
    const name = image.name || base?.split('/').pop();
    const path = image.path || base;

    const isAbs = isAbsoluteFilePath(path);
    const hasAssetBridge =
      typeof window !== 'undefined' &&
      isAbs &&
      window?.tauriAPI?.filePathToAssetUrl;

    // Desktop: convert absolute on-disk paths (e.g. /System/Library/...) into
    // WebView-loadable asset URLs. If the bridge isn't ready yet, do NOT keep
    // the raw absolute path in the <img> tag (WebView will reject it).
    const convertedPath = hasAssetBridge
      ? window.tauriAPI.filePathToAssetUrl(path)
      : (isAbs ? null : path);

    // Keep the original file path around for stable selection/transcode.
    const filePath = isAbs ? path : (image.filePath || null);

    return {
      ...image,
      name,
      filePath,
      path: toSafeUrl(convertedPath),
      // NOTE: for absolute file paths we do not try to derive '/thumbs/' variants.
      thumbPath: toSafeUrl(
        hasAssetBridge
          ? convertedPath
          : (convertedPath ? deriveThumbnail(image.thumbPath || convertedPath) : null)
      ),
    };
  }),
});

const BackgroundsTab = ({
  options,
  setOptions,
  blob,
  wallpaperCategories,
  isPremium = false,
  showWallpapers = true,
  showEffects = true,
}) => {
  const { t } = useI18n();
  const [tauriBridgeNonce, setTauriBridgeNonce] = useState(0);
  const uploadTileBg = null;
  // Allow custom uploads everywhere (web + desktop). In the desktop shell we additionally
  // persist the file into an app-managed folder via tauriAPI.
  const canUploadCustom =
    typeof window !== 'undefined' &&
    typeof window.FileReader !== 'undefined';
  const [loadingWallpaper, setLoadingWallpaper] = useState(false);
  const [selectedWallpaperId, setSelectedWallpaperId] = useState(null);
  const [failedPaths, setFailedPaths] = useState(new Set());
  const [displayCategories, setDisplayCategories] = useState(defaultLocalCategories);
  const [customWallpapers, setCustomWallpapers] = useState([]);
  const [systemWallpapers, setSystemWallpapers] = useState([]);
  const [autoGenerated, setAutoGenerated] = useState([]);
  const [algorithmGradients, setAlgorithmGradients] = useState([]);

  const autoHideGuardRef = useRef({ restore: null, timer: null });
  const wallpaperLoadTokenRef = useRef(0);
  const systemWallpapersLoadTokenRef = useRef(0);

  // In desktop builds, ensure the tauri bridge is installed before we normalize
  // wallpaper catalog entries (some are absolute paths like /System/...).
  // If this component renders before pages/_app finishes installTauriApi(),
  // we would otherwise keep raw paths and hit "unsupported URL" errors.
  useEffect(() => {
    let cancelled = false;
    const run = async () => {
      try {
        const mod = await import('../../utils/platform/tauriApi');
        if (mod?.installTauriApi) {
          await mod.installTauriApi();
        }
      } catch {
        // ignore
      }
      if (!cancelled) setTauriBridgeNonce((n) => n + 1);
    };
    run();
    return () => { cancelled = true; };
  }, []);

  const getCategoryLabel = useCallback((name) => {
    switch (name) {
      case 'System Wallpapers':
        return t('categorySystemWallpapers');
      case 'Auto-Generated':
        return t('categoryAutoGenerated');
      case 'Gradients':
        return t('categoryGradients');
      case 'Custom Backgrounds':
        return t('categoryCustomBackgrounds');
      case 'macOS Wallpapers':
        return t('categoryMacosWallpapers');
      default:
        return name;
    }
  }, [t]);

  const beginNativeDialogGuard = useCallback(() => {
    const api = (typeof window !== 'undefined' && (window.tauriAPI || window.electronAPI)) ? (window.tauriAPI || window.electronAPI) : null;
    const setAutoHideEnabled = api?.setAutoHideEnabled;
    if (typeof setAutoHideEnabled !== 'function') return;

    const getDesiredAutoHide = () => {
      try {
        const raw = window?.localStorage?.getItem?.('settings.autoHideEnabled');
        if (raw == null) return true;
        // Stored via setJson(boolean) => "true" | "false"
        const parsed = JSON.parse(raw);
        return !!parsed;
      } catch {
        return true;
      }
    };

    // Disable auto-hide before the OS dialog steals focus.
    try { setAutoHideEnabled(false); } catch {}

    const restore = () => {
      try { setAutoHideEnabled(getDesiredAutoHide()); } catch {}
      if (autoHideGuardRef.current?.timer) {
        clearTimeout(autoHideGuardRef.current.timer);
      }
      autoHideGuardRef.current = { restore: null, timer: null };
    };

    autoHideGuardRef.current.restore = restore;

    const onFocus = () => restore();
    // When the native file picker closes, focus usually returns.
    try {
      window.addEventListener('focus', onFocus, { once: true });
    } catch {
      window.addEventListener('focus', onFocus);
      setTimeout(() => window.removeEventListener('focus', onFocus), 0);
    }

    // Safety net in case focus event never fires (e.g. cancelled dialog quirks).
    autoHideGuardRef.current.timer = setTimeout(restore, 15000);
  }, []);

  const generateAlgorithmGradients = useCallback(async () => {
    try {
      if (typeof document === 'undefined') return;

      const renderThumb = async (background) => {
        const src = document.createElement('canvas');
        const dst = document.createElement('canvas');
        const full = 220;
        const out = 160;
        const margin = Math.floor((full - out) / 2);
        await renderBackgroundToCanvas({
          outCanvas: src,
          widthCssPx: full,
          heightCssPx: full,
          renderScale: 1,
          background,
          blurPx: 0,
          brightness: 1,
          wallpaperImage: null,
        });
        dst.width = out;
        dst.height = out;
        const ctx = dst.getContext('2d');
        if (!ctx) throw new Error('no ctx');
        ctx.drawImage(src, margin, margin, out, out, 0, 0, out, out);
        return dst.toDataURL('image/png');
      };

      // Deterministic, hand-picked linear gradients.
      // IMPORTANT: this is separate from auto-generated gradients and does not affect them.
      const linearDefs = [
        { key: 'gradientPurpleOrange', colorStart: '#6D28D9', colorEnd: '#EA580C', angleDeg: 135 },
        { key: 'gradientTealMagenta', colorStart: '#0D9488', colorEnd: '#C026D3', angleDeg: 135 },
        { key: 'gradientBlueCyan', colorStart: '#1D4ED8', colorEnd: '#0891B2', angleDeg: 135 },
        { key: 'gradientVioletPink', colorStart: '#7C3AED', colorEnd: '#DB2777', angleDeg: 135 },
        { key: 'gradientLimeTeal', colorStart: '#65A30D', colorEnd: '#0D9488', angleDeg: 135 },
        { key: 'gradientIndigoFuchsia', colorStart: '#4338CA', colorEnd: '#A21CAF', angleDeg: 135 },
        { key: 'gradientEmber', colorStart: '#C2410C', colorEnd: '#BE123C', angleDeg: 135 },
        { key: 'gradientMidnightNeon', colorStart: '#0369A1', colorEnd: '#15803D', angleDeg: 135 },
        { key: 'gradientDusk', colorStart: '#111827', colorEnd: '#6D28D9', angleDeg: 135 },

        // Extra linear gradients (restored/expanded catalog)
        { key: 'gradientCandyPurple', colorStart: '#7C3AED', colorEnd: '#F97316', angleDeg: 135 },
        { key: 'gradientNeonMint', colorStart: '#22C55E', colorEnd: '#06B6D4', angleDeg: 135 },
        { key: 'gradientOceanBlue', colorStart: '#0EA5E9', colorEnd: '#1D4ED8', angleDeg: 135 },
        { key: 'gradientSunset', colorStart: '#F97316', colorEnd: '#DB2777', angleDeg: 135 },
        { key: 'gradientMidnight', colorStart: '#0B1020', colorEnd: '#7700FF', angleDeg: 135 },
        { key: 'gradientLava', colorStart: '#DC2626', colorEnd: '#F97316', angleDeg: 135 },
        { key: 'gradientAurora', colorStart: '#22C55E', colorEnd: '#A855F7', angleDeg: 135 },
        { key: 'gradientRoseGold', colorStart: '#FB7185', colorEnd: '#F59E0B', angleDeg: 135 },
        { key: 'gradientIce', colorStart: '#38BDF8', colorEnd: '#A5F3FC', angleDeg: 135 },
      ];

      // Curated blob gradients adapted from user-provided multi-layer CSS gradients.
      // The renderer supports linear/blob modes, so we map those CSS stacks into blob configs.
      const blobDefs = [
        {
          key: 'gradientCandyNebula',
          config: {
            baseMode: 'light',
            baseA: '#3182ce',
            baseB: '#4fd1c5',
            colors: ['#feb2b2', 'rgba(252, 184, 219, 0.75)', 'rgba(239, 194, 250, 0.5)', '#348fc5', '#389ac2', '#3ca5c1', '#41b0c2', '#45bbc3'],
            seed: 910001,
            blobCount: 9,
            intensity: 0.74,
            angleDeg: 135,
          },
        },
        {
          key: 'gradientAuroraFog',
          config: {
            baseMode: 'light',
            baseA: '#fdd575',
            baseB: '#d22e8c',
            colors: ['#4964da', 'rgba(146, 73, 221, 0.8)', 'rgba(176, 60, 196, 0.6)', 'rgba(192, 55, 173, 0.4)', '#fcc06a', '#fbaa63', '#f99262', '#f55973'],
            seed: 910002,
            blobCount: 9,
            intensity: 0.76,
            angleDeg: 163,
          },
        },
        {
          key: 'gradientRoseSmoke',
          config: {
            baseMode: 'light',
            baseA: 'hsla(173, 77%, 83%, 1)',
            baseB: 'hsla(173, 77%, 83%, 1)',
            colors: ['hsla(250, 76%, 61%, 1)', 'hsla(184, 91%, 91%, 1)', 'hsla(213, 97%, 75%, 1)', 'hsla(149, 93%, 64%, 1)', 'hsla(118, 94%, 89%, 1)'],
            seed: 910003,
            blobCount: 8,
            intensity: 0.74,
            angleDeg: 146,
          },
        },
        {
          key: 'gradientDeepOceanGlow',
          config: {
            baseMode: 'dark',
            baseA: 'hsla(327, 100%, 50%, 1)',
            baseB: 'hsla(327, 100%, 50%, 1)',
            colors: ['hsla(11, 100%, 50%, 1)', 'hsla(236, 100%, 23%, 1)', 'hsla(206, 100%, 9%, 1)', 'hsla(327, 100%, 50%, 1)'],
            seed: 910004,
            blobCount: 8,
            intensity: 0.82,
            angleDeg: 142,
          },
        },
      {
          key: 'gradientElectricViolet',
          config: {
            baseMode: 'light',
            baseA: 'hsla(197, 92%, 60%, 1)',
            baseB: 'hsla(197, 92%, 60%, 1)',
            colors: ['hsla(55, 93%, 54%, 0.85)', 'hsla(229, 71%, 68%, 1)', 'hsla(308, 93%, 51%, 1)', 'hsla(318, 60%, 76%, 1)', 'hsla(324, 92%, 59%, 1)'],
            seed: 910005,
            blobCount: 9,
            intensity: 0.76,
            angleDeg: 138,
          },
        },
        {
          key: 'gradientBerry',
          config: {
            baseMode: 'light',
            baseA: 'hsla(259, 100%, 63%, 1)',
            baseB: 'hsla(259, 100%, 63%, 1)',
            colors: ['hsla(318, 80%, 97%, 1)', 'hsla(161, 99%, 84%, 1)', 'hsla(163, 90%, 78%, 1)', 'hsla(314, 91%, 59%, 1)'],
            seed: 910006,
            blobCount: 9,
            intensity: 0.74,
            angleDeg: 132,
          },
        },
        {
          key: 'gradientIce',
          config: {
            baseMode: 'light',
            baseA: 'hsla(259, 84%, 37%, 1)',
            baseB: 'hsla(259, 84%, 37%, 1)',
            colors: ['hsla(248, 82%, 99%, 1)', 'hsla(318, 83%, 77%, 1)', 'hsla(302, 95%, 45%, 1)', 'hsla(210, 87%, 65%, 1)', 'hsla(317, 98%, 84%, 1)'],
            seed: 910007,
            blobCount: 9,
            intensity: 0.75,
            angleDeg: 136,
          },
        },
        {
          key: 'gradientSkyline',
          config: {
            baseMode: 'light',
            baseA: 'hsla(185, 58%, 56%, 1)',
            baseB: 'hsla(185, 58%, 56%, 1)',
            colors: ['hsla(253, 66%, 75%, 1)', 'hsla(226, 66%, 63%, 1)', 'hsla(359, 63%, 67%, 1)', 'hsla(181, 88%, 59%, 1)', 'hsla(293, 91%, 54%, 1)', 'hsla(293, 89%, 59%, 1)', 'hsla(197, 99%, 92%, 1)', 'hsla(251, 96%, 90%, 1)', 'hsla(270, 63%, 55%, 1)', 'hsla(278, 99%, 97%, 1)'],
            seed: 910008,
            blobCount: 9,
            intensity: 0.76,
            angleDeg: 129,
          },
        },
        {
          key: 'gradientDeepSea',
          config: {
            baseMode: 'light',
            baseA: 'hsla(204, 0%, 100%, 1)',
            baseB: 'hsla(204, 0%, 100%, 1)',
            colors: ['hsla(295, 77%, 74%, 0.35)', 'hsla(236, 77%, 74%, 0.35)', 'hsla(186, 77%, 74%, 0.35)', 'hsla(127, 77%, 74%, 0.35)', 'hsla(62, 77%, 74%, 0.35)', 'hsla(23, 77%, 74%, 0.35)'],
            seed: 910009,
            blobCount: 9,
            intensity: 0.70,
            angleDeg: 135,
          },
        },
      ];

      const items = [
        ...linearDefs.map((d) => ({
          kind: 'gradient',
          name: t(d.key),
          config: {
            colorStart: d.colorStart,
            colorEnd: d.colorEnd,
            angleDeg: d.angleDeg,
          },
          path: null,
          thumbPath: null,
        })),
        ...blobDefs.map((d) => ({
          kind: 'blobGradient',
          name: t(d.key),
          config: {
            ...(d.config || {}),
          },
          path: null,
          thumbPath: null,
        })),
      ];

      const thumbs = await Promise.all(items.map(async (it) => {
        try {
          const dataUrl = await renderThumb(
            it.kind === 'blobGradient'
              ? { type: 'blobGradient', config: it.config }
              : { type: 'gradient', colorStart: it.config?.colorStart, colorEnd: it.config?.colorEnd, angleDeg: it.config?.angleDeg }
          );
          return { ...it, path: dataUrl, thumbPath: dataUrl };
        } catch {
          return it;
        }
      }));

      setAlgorithmGradients(thumbs);
    } catch (e) {
      console.error('Failed to generate algorithm gradients:', e);
      setAlgorithmGradients([]);
    }
  }, [t]);

  const applyBlobGradient = useCallback((config) => {
    setOptions((prev) => {
      if (isSameBlobGradientSelection(prev, config)) {
        return toggleBlobGradientOff(prev, baseOptions?.customTheme);
      }

      return {
        ...prev,
        backgroundType: 'blobGradient',
        blobGradient: {
          ...(config || {}),
        },
        wallpaper: null,
        wallpaperSource: null,
        wallpaperPath: null,
      };
    });
  }, [setOptions]);

  const applyGradient = useCallback((config) => {
    setOptions((prev) => {
      if (isSameGradientSelection(prev, config)) {
        return toggleGradientOff(prev, baseOptions?.customTheme);
      }

      return {
        ...prev,
        backgroundType: 'gradient',
        customTheme: {
          ...(prev?.customTheme || {}),
          colorStart: config?.colorStart || prev?.customTheme?.colorStart,
          colorEnd: config?.colorEnd || prev?.customTheme?.colorEnd,
        },
        wallpaper: null,
        wallpaperSource: null,
        wallpaperPath: null,
      };
    });
  }, [setOptions]);

  const generateAutoGradients = useCallback(async () => {
    const src = blob?.src;
    if (!src) {
      setAutoGenerated([]);
      return;
    }

    try {
      const palette = await extractPaletteFromDataUrl(src, { colorCount: 7, returnMeta: true });
      const colors = (Array.isArray(palette) ? palette : palette?.colors || []).filter(Boolean);
      const weights = Array.isArray(palette?.weights) ? palette.weights : [];

      const fallback = ['#8B5CF6', '#EC4899', '#22C55E', '#06B6D4', '#F59E0B', '#0EA5E9', '#A855F7'];

      const buildWeightedColors = (cols, wts) => {
        if (!cols.length) return [];
        const maxSlots = 8;
        if (!wts.length) return cols.slice(0, maxSlots);
        const total = wts.reduce((sum, w) => sum + (Number.isFinite(w) ? w : 0), 0) || 1;
        const expanded = [];
        cols.forEach((c, i) => {
          const w = Number.isFinite(wts[i]) ? wts[i] : (1 / cols.length);
          const count = Math.max(1, Math.round((w / total) * maxSlots));
          for (let k = 0; k < count; k++) expanded.push(c);
        });
        if (expanded.length < maxSlots) {
          const sorted = cols
            .map((c, i) => ({ c, w: Number.isFinite(wts[i]) ? wts[i] : 0 }))
            .sort((a, b) => b.w - a.w);
          let idx = 0;
          while (expanded.length < maxSlots && sorted.length) {
            expanded.push(sorted[idx % sorted.length].c);
            idx += 1;
          }
        }
        return expanded.slice(0, maxSlots);
      };

      const weightedColors = buildWeightedColors(colors, weights);
      const base = weightedColors.length ? weightedColors : (colors.length ? colors : fallback);

      const getRandomU32 = () => {
        try {
          if (typeof crypto !== 'undefined' && crypto?.getRandomValues) {
            const u = new Uint32Array(1);
            crypto.getRandomValues(u);
            return u[0] >>> 0;
          }
        } catch {}
        return (Math.floor(Math.random() * 2 ** 32) >>> 0);
      };

      const mulberry32 = (a) => {
        let t = a >>> 0;
        return () => {
          t += 0x6D2B79F5;
          let x = Math.imul(t ^ (t >>> 15), 1 | t);
          x ^= x + Math.imul(x ^ (x >>> 7), 61 | x);
          return ((x ^ (x >>> 14)) >>> 0) / 4294967296;
        };
      };

      const baseSeed = getRandomU32();
      const rand = mulberry32(baseSeed);

      const pickColors = (count = 8) => {
        const pool = base.length ? base : fallback;
        const out = [];
        for (let i = 0; i < count; i += 1) {
          out.push(pool[Math.floor(rand() * pool.length)]);
        }
        return out;
      };

      const mk = (i) => {
        const baseMode = rand() < 0.55 ? 'dark' : 'light';
        const blobCount = Math.max(5, Math.min(11, 6 + Math.floor(rand() * 5)));
        const intensity = 0.70 + rand() * 0.18;
        const angleDeg = Math.floor(30 + rand() * 300);
        return {
          kind: 'blobGradient',
          name: t('autoGradientName', { n: i + 1 }),
          config: {
            colors: pickColors(8),
            seed: (baseSeed + i * 9973) >>> 0,
            blobCount,
            intensity,
            angleDeg,
            baseMode,
            baseA: baseMode === 'light' ? '#FFFFFF' : '#000000',
            baseB: baseMode === 'light' ? '#FFFFFF' : '#000000',
            blend: baseMode === 'light' ? 'multiply' : 'screen',
          },
          path: null,
          thumbPath: null,
        };
      };

      const items = Array.from({ length: 12 }, (_v, i) => mk(i));

      const renderThumb = async (background) => {
        const srcCanvas = document.createElement('canvas');
        const dstCanvas = document.createElement('canvas');
        const full = 220;
        const out = 160;
        const margin = Math.floor((full - out) / 2);
        await renderBackgroundToCanvas({
          outCanvas: srcCanvas,
          widthCssPx: full,
          heightCssPx: full,
          renderScale: 1,
          background,
          blurPx: 0,
          brightness: 1,
          wallpaperImage: null,
        });
        dstCanvas.width = out;
        dstCanvas.height = out;
        const ctx = dstCanvas.getContext('2d');
        if (!ctx) throw new Error('no ctx');
        ctx.drawImage(srcCanvas, margin, margin, out, out, 0, 0, out, out);
        return dstCanvas.toDataURL('image/png');
      };

      // Pre-render thumbs to data URLs so the section looks identical to other wallpaper sections.
      const thumbs = await Promise.all(items.map(async (it) => {
        try {
          const dataUrl = await renderThumb({ type: 'blobGradient', config: it.config });
          return { ...it, path: dataUrl, thumbPath: dataUrl };
        } catch {
          return it;
        }
      }));

      setAutoGenerated(thumbs);
    } catch (e) {
      console.error('Failed to generate auto gradients:', e);
      setAutoGenerated([]);
    }
  }, [blob?.src, t]);

  const loadCustomWallpapers = useCallback(async () => {
    try {
      if (!window?.tauriAPI?.listCustomBackgrounds) {
        setCustomWallpapers([]);
        return;
      }
      const list = await window.tauriAPI.listCustomBackgrounds();
      const items = Array.isArray(list) ? list : [];
      const thumbs = await Promise.all(items.map(async (item) => {
        try {
          // Thumbnails only: keep these small to avoid UI memory bloat.
          //Is this code even used? Request for deletion consideration.
          const thumbUrl = await window.tauriAPI.readFileAsAssetUrl({ filePath: item.filePath, maxDim: 256 });
          return { ...item, thumbUrl };
        } catch {
          return { ...item, thumbUrl: null };
        }
      }));
      setCustomWallpapers(thumbs.filter((x) => !!x.thumbUrl));
    } catch (e) {
      console.error('Failed to load custom wallpapers:', e);
      setCustomWallpapers([]);
    }
  }, [tauriBridgeNonce]);

  const loadSystemWallpapers = useCallback(async () => {
    const loadToken = (systemWallpapersLoadTokenRef.current + 1);
    systemWallpapersLoadTokenRef.current = loadToken;

    try {
      if (!window?.tauriAPI?.listSystemWallpapers || (!window?.tauriAPI?.filePathToAssetUrl && !window?.tauriAPI?.readFileAsAssetUrl)) {
        setSystemWallpapers([]);
        return;
      }

      const res = await window.tauriAPI.listSystemWallpapers({ maxItems: 150 });
      const items = Array.isArray(res) ? res : [];

      const needsTranscodeForImgTag = (filePath) => {
        const s = String(filePath || '').toLowerCase();
        return s.endsWith('.heic') || s.endsWith('.heif') || s.endsWith('.avif');
      };

      const baseMapped = items.map((it) => {
        const filePath = it?.filePath || it?.file_path || it?.path || null;
        if (!filePath) return null;
        const name = it?.name || String(filePath).split(/[\\/]/).pop() || 'Wallpaper';

        const assetUrl = window?.tauriAPI?.filePathToAssetUrl
          ? window.tauriAPI.filePathToAssetUrl(filePath)
          : null;

        return { name, filePath, assetUrl, thumbUrl: null };
      }).filter(Boolean);

      // Clear first, then stream only renderable items (with generated thumbs).
      // This avoids showing placeholder/empty tiles when some sources are unreadable.
      setSystemWallpapers([]);

      const resolved = [];

      // Stream in thumbnails in small batches to keep UI responsive.
      const limit = 6;
      for (let i = 0; i < baseMapped.length; i += limit) {
        if (systemWallpapersLoadTokenRef.current !== loadToken) return;
        const chunk = baseMapped.slice(i, i + limit);
        const part = await Promise.all(chunk.map(async (item) => {
          const filePath = item?.filePath;
          if (!filePath) return { filePath: null, thumbUrl: null };

          try {
            if (window?.tauriAPI?.readFileAsAssetUrl) {
              const url = await window.tauriAPI.readFileAsAssetUrl({ filePath, maxDim: 256 });
              if (url) return { filePath, thumbUrl: String(url) };
            }
          } catch (e) {
            console.warn('[System Wallpapers] Failed to generate thumbnail:', { filePath, error: String(e?.message || e) });
          }

          return { filePath, thumbUrl: null };
        }));

        const byPath = new Map(part.filter((x) => x?.filePath && x?.thumbUrl).map((x) => [x.filePath, x.thumbUrl]));
        for (const item of chunk) {
          const nextThumb = item?.filePath ? byPath.get(item.filePath) : null;
          if (nextThumb) {
            resolved.push({ ...item, thumbUrl: nextThumb });
          }
        }

        if (systemWallpapersLoadTokenRef.current !== loadToken) return;
        setSystemWallpapers([...resolved]);

        await new Promise((r) => setTimeout(r, 0));
      }
    } catch (e) {
      console.error('Failed to load system wallpapers:', e);
      setSystemWallpapers([]);
    }
  }, [tauriBridgeNonce]);
  
  // Function to apply a wallpaper
  // For custom wallpapers we display an asset URL, but persist a stable on-disk filePath
  // so presets/localStorage don't bloat and can rehydrate later.
  const selectWallpaper = async (wallpaperPath, wallpaperId, source = 'local', stableWallpaperPath = null) => {
    if (loadingWallpaper) return; // Prevent multiple concurrent loads
    const loadToken = (wallpaperLoadTokenRef.current + 1);
    wallpaperLoadTokenRef.current = loadToken;

    const candidatePath = stableWallpaperPath || wallpaperPath;
    if (candidatePath) {
      let didToggleOff = false;
      setOptions((prev) => {
        if (isSameWallpaperSelection(prev, candidatePath)) {
          didToggleOff = true;
          return toggleWallpaperOff(prev);
        }
        return prev;
      });
      if (didToggleOff) return;
    }
    
    // Immediately mark this wallpaper as selected for UI feedback
    setSelectedWallpaperId(wallpaperId);
    setLoadingWallpaper(true);
    
    try {
      let wallpaperUrl = wallpaperPath;
      if (wallpaperPath.startsWith('/') && wallpaperPath.includes('/thumbs/')) {
        wallpaperUrl = wallpaperPath.replace('/backgrounds/thumbs/', '/backgrounds/');
      }

      wallpaperUrl = toSafeUrl(wallpaperUrl);

      // If the tile is using a placeholder (or missing URL), derive a quick preview from the stable path.
      if ((!wallpaperUrl || wallpaperUrl === FALLBACK_PIXEL_PNG) && stableWallpaperPath && window?.tauriAPI?.filePathToAssetUrl) {
        try {
          const preview = window.tauriAPI.filePathToAssetUrl(String(stableWallpaperPath));
          if (preview) wallpaperUrl = toSafeUrl(preview);
        } catch {}
      }

      const nextWallpaperPath = stableWallpaperPath || wallpaperPath;

      const applyWallpaperOptions = (url, { force = false } = {}) => {
        if (wallpaperLoadTokenRef.current !== loadToken) return;
        setOptions((prev) => {
          if (!force) {
            if (prev?.backgroundType !== 'wallpaper') return prev;
            if (prev?.wallpaperPath && prev.wallpaperPath !== nextWallpaperPath) return prev;
          }
          return {
            ...prev,
            backgroundType: 'wallpaper',
            wallpaper: url,
            wallpaperSource: source,
            wallpaperPath: nextWallpaperPath,
          };
        });
      };

      // Important: never store huge base64 data URLs in the global options state.
      // For custom wallpapers, store the stable on-disk filePath and let ImageDisplay
      // rehydrate it via tauriAPI when rendering.
      const shouldUseStablePathForWallpaper =
        !!stableWallpaperPath &&
        (source === 'custom' || source === 'system' || isAbsoluteFilePath(stableWallpaperPath));
      if (shouldUseStablePathForWallpaper) {
        // Apply a fast preview immediately (thumb/asset URL).
        applyWallpaperOptions(wallpaperUrl, { force: true });

        if (source === 'custom' && window?.tauriAPI?.readFileAsAssetUrl) {
          try {
            const fullUrl = await window.tauriAPI.readFileAsAssetUrl({ filePath: stableWallpaperPath });
            if (fullUrl) applyWallpaperOptions(fullUrl);
          } catch {}
        }

        // Treat any absolute file path like a "system" wallpaper for URL generation.
        if (source === 'system' || isAbsoluteFilePath(stableWallpaperPath)) {
          const fp = String(stableWallpaperPath || '');
          const lower = fp.toLowerCase();
          const needsTranscode = lower.endsWith('.heic') || lower.endsWith('.heif') || lower.endsWith('.avif');

          if (window?.tauriAPI?.filePathToAssetUrl) {
            const assetUrl = window.tauriAPI.filePathToAssetUrl(fp);
            if (assetUrl) applyWallpaperOptions(assetUrl);
          }

          // If filePathToAssetUrl is unavailable (or the format is not <img>/<css> friendly),
          // fall back to a generated asset URL.
          const shouldGenerateAsset = needsTranscode || !window?.tauriAPI?.filePathToAssetUrl;
          if (shouldGenerateAsset && window?.tauriAPI?.readFileAsAssetUrl) {
            try {
              // Keep this large enough for good visual quality but still bounded.
              const fullUrl = await window.tauriAPI.readFileAsAssetUrl({ filePath: fp, maxDim: 4096 });
              if (fullUrl) applyWallpaperOptions(fullUrl);
            } catch {}
          }
        }
      } else {
        applyWallpaperOptions(wallpaperUrl, { force: true });
      }
      // Intentionally silent in production.
    } catch (error) {
      console.error("Error loading wallpaper:", error);
      setFailedPaths(prev => new Set([...prev, wallpaperPath]));
    } finally {
      // Reset loading states
      setLoadingWallpaper(false);
      
      // Clear selection after a brief moment
      setTimeout(() => {
        setSelectedWallpaperId(null);
      }, 300);
    }
  };

  // Function to retry all failed wallpapers
  const retryFailedWallpapers = () => {
    setFailedPaths(new Set());
    // Intentionally silent in production.
  };

  // Handle wallpaper upload - persist to app folder when running in the desktop app
  const handleWallpaperUpload = async (event) => {
    const file = event.target.files[0];
    if (file && file.type.includes('image')) {
      try {
        const reader = new FileReader();
        reader.onload = function (e) {
          const dataUrl = e.target.result;
          const run = async () => {
            let savedName = file.name;
            let savedFilePath = null;
            // Save to app-managed folder when available
            if (window?.tauriAPI?.saveCustomBackground) {
              try {
                const res = await window.tauriAPI.saveCustomBackground({ dataUrl, fileName: file.name });
                if (!res || res.ok !== true) {
                  throw new Error(res?.error || 'Failed to save custom background');
                }
                savedName = res?.name || savedName;
                savedFilePath = res?.filePath || null;
                await loadCustomWallpapers();
              } catch (err) {
                console.error('Failed to save custom background:', err);
              }
            }
            const wallpaperUrl = savedFilePath && window?.tauriAPI?.readFileAsAssetUrl
              ? await window.tauriAPI.readFileAsAssetUrl({ filePath: savedFilePath })
              : (savedFilePath ? savedFilePath : dataUrl);
            setOptions(prev => ({
              ...prev,
              backgroundType: 'wallpaper',
              wallpaper: wallpaperUrl,
              wallpaperSource: 'custom',
              // Keep this small/stable so it can be used later (e.g. delete-active checks).
              wallpaperPath: savedFilePath || savedName,
            }));
            // Intentionally silent in production.
          };
          run();
        };
        reader.onerror = function (e) {
          console.error('Failed to read image file');
        };
        reader.readAsDataURL(file);
      } catch (err) {
        console.error("Error handling wallpaper upload:", err);
      } finally {
        try { autoHideGuardRef.current?.restore?.(); } catch {}
      }
    }
  };

  const deleteCustomWallpaper = async (image) => {
    try {
      const filePath = image?.filePath;
      if (!filePath) return;
      if (!window?.tauriAPI?.deleteCustomBackground) return;
      const res = await window.tauriAPI.deleteCustomBackground(filePath);
      if (!res || res.ok !== true) {
        throw new Error(res?.error || 'Failed to delete custom background');
      }

      // If the deleted wallpaper is currently active, reset back to gradient.
      const isActiveCustom = options?.wallpaperSource === 'custom';
      const matchesActive =
        options?.wallpaperPath === image?.filePath ||
        options?.wallpaperPath === image?.name ||
        options?.wallpaperPath === image?.path ||
        options?.wallpaper === image?.path;

      if (isActiveCustom && matchesActive) {
        setOptions((prev) => ({
          ...prev,
          backgroundType: 'gradient',
          wallpaper: null,
          wallpaperSource: null,
          wallpaperPath: null,
        }));
      }

      await loadCustomWallpapers();
    } catch (e) {
      console.error('Failed to delete custom wallpaper:', e);
    }
  };

  // Check if a wallpaper tile is currently selected.
  // Avoid substring scans against large data: URLs (these were causing massive UI lag).
  const isSelectedWallpaper = (image) => {
    const active = options?.wallpaper;
    if (!active) return false;

    // Custom: match by stable filePath/name stored in wallpaperPath.
    if (options?.wallpaperSource === 'custom' || options?.wallpaperSource === 'system') {
      const activePath = options?.wallpaperPath || active;
      const candidate = image?.filePath || image?.name || image?.path;
      return !!activePath && !!candidate && activePath === candidate;
    }

    // Local: compare exact paths.
    const candidate = image?.path;
    return !!candidate && (active === candidate || options?.wallpaperPath === candidate);
  };
  
  // Update displayCategories when wallpaperCategories change
  useEffect(() => {
    const baseCategories = (wallpaperCategories && wallpaperCategories.length > 0)
      ? wallpaperCategories
      : defaultLocalCategories;

    const safeBase = Array.isArray(baseCategories) ? baseCategories : [];

    {
      const mergedCategories = safeBase.map((category) => ({
        ...normalizeCategory(category),
        displayName: getCategoryLabel(category?.name),
      }));

      const autoCategory = normalizeCategory({
        name: 'Auto-Generated',
        path: 'Auto-Generated/',
        source: 'generated',
        images: autoGenerated,
        displayName: getCategoryLabel('Auto-Generated'),
      });

      const gradientsCategory = normalizeCategory({
        name: 'Gradients',
        path: 'Gradients/',
        source: 'generated',
        images: algorithmGradients,
        displayName: getCategoryLabel('Gradients'),
      });
      const customCategory = normalizeCategory({
        name: 'Custom Backgrounds',
        path: 'Custom Backgrounds/',
        source: 'custom',
        displayName: getCategoryLabel('Custom Backgrounds'),
        images: (customWallpapers || []).map((item) => ({
          name: item.name,
          path: item.thumbUrl,
          thumbPath: item.thumbUrl,
          filePath: item.filePath,
        })),
      });

      const systemCategory = normalizeCategory({
        name: 'System Wallpapers',
        path: 'System Wallpapers/',
        source: 'system',
        displayName: getCategoryLabel('System Wallpapers'),
        images: (systemWallpapers || [])
          .map((it) => ({
            name: it.name,
            // Only include tiles that have an actual generated thumbnail.
            // This keeps tile count aligned to what is truly renderable.
            path: it.thumbUrl || null,
            thumbPath: it.thumbUrl || null,
            filePath: it.filePath,
          }))
          .filter((it) => !!it.path),
      });

      const withAuto = autoGenerated && autoGenerated.length > 0 ? [autoCategory] : [];
      const withGradients = algorithmGradients && algorithmGradients.length > 0 ? [gradientsCategory] : [];


	  // Order requested:
	  // 1) Upload tile (Custom Backgrounds)
	  // 2) Transparent toggle (rendered separately below)
	  // 3) Gradients
	  // 4) macOS Wallpapers
	  // 5) The rest (Auto-Generated + remaining categories)
    
    // Above system seems like our old code for a UI that rendered backgrounds in 1 big list. Consider deletion.
	  const macos = mergedCategories.find((c) => c?.name === 'macOS Wallpapers');
	  const rest = mergedCategories.filter((c) => c?.name !== 'macOS Wallpapers');

    const withSystem = systemWallpapers && systemWallpapers.length > 0 ? [systemCategory] : [];

    setDisplayCategories([
    customCategory,
    ...withGradients,
    ...withSystem,
    ...(macos ? [macos] : []),
    ...withAuto,
    ...rest,
    ]);
    }
  }, [wallpaperCategories, customWallpapers, systemWallpapers, autoGenerated, algorithmGradients, getCategoryLabel, tauriBridgeNonce]);

  // Generate auto gradients automatically when a screenshot is available.
  useEffect(() => {
    generateAutoGradients();
  }, [generateAutoGradients]);

  // Load custom wallpapers once on mount (desktop only), and retry after the Tauri bridge installs.
  useEffect(() => {
    loadCustomWallpapers();
  }, [loadCustomWallpapers]);

  // Load system wallpapers once on mount (desktop only).
  useEffect(() => {
    loadSystemWallpapers();
  }, [loadSystemWallpapers]);

  // Generate algorithm gradients once on mount.
  useEffect(() => {
    generateAlgorithmGradients();
  }, [generateAlgorithmGradients]);

  const categories = Array.isArray(displayCategories) ? displayCategories : [];
  const customCategory = categories.find((c) => c?.name === 'Custom Backgrounds' || c?.source === 'custom') || null;
  const otherCategories = categories.filter((c) => c && c !== customCategory);

  const renderCategoryCard = (category) => {
    const isCustomCategory = category?.name === 'Custom Backgrounds' || category?.source === 'custom';
    const isAutoGradientsCategory = category?.name === 'Auto-Generated' || category?.source === 'auto-generated';
    const isSystemWallpapersCategory = category?.name === 'System Wallpapers' || category?.source === 'system';
    const categoryLabel = category?.displayName || getCategoryLabel(category?.name);

    return (
      <div className="sidebar-flat-section" key={`cat:${String(category?.name || categoryLabel || 'unknown')}`}>
        <div className="px-4 pt-3 pb-2">
          <div className="flex items-center gap-2">
            <span className="text-xs text-[color:var(--app-muted)]">{categoryLabel}</span>
            {isAutoGradientsCategory && (
              <span
                className="text-[10px] px-2 py-0.5 rounded-full border"
                style={{
                  borderColor: 'var(--card-border)',
                  background: 'var(--chip-bg)',
                  color: 'var(--app-muted)',
                }}
              >
                {t('beta')}
              </span>
            )}
            {isSystemWallpapersCategory && (
              <span
                className="text-[10px] px-2 py-0.5 rounded-full border"
                style={{
                  borderColor: 'var(--card-border)',
                  background: 'var(--chip-bg)',
                  color: 'var(--app-muted)',
                }}
              >
                Experimental
              </span>
              // experimental tag not showing in run
            )}
          </div>
        </div>

        <div className="px-4 pb-4">
          <div className="grid grid-cols-3 gap-3">
            {isCustomCategory && (
              <label
                className={
                  `custom-wallpaper-upload-tile group relative rounded-2xl overflow-hidden border aspect-square ` +
                  (canUploadCustom ? 'cursor-pointer' : 'cursor-not-allowed opacity-60')
                }
                title={canUploadCustom ? t('uploadCustomBackground') : t('customUploadsUnavailable')}
                onMouseDown={() => { if (canUploadCustom) beginNativeDialogGuard(); }}
                onTouchStart={() => { if (canUploadCustom) beginNativeDialogGuard(); }}
                onClick={() => { if (canUploadCustom) beginNativeDialogGuard(); }}
                onKeyDown={() => { if (canUploadCustom) beginNativeDialogGuard(); }}
              >
                <input
                  type="file"
                  accept="image/*"
                  onChange={canUploadCustom ? handleWallpaperUpload : undefined}
                  disabled={!canUploadCustom}
                  className="hidden"
                />
                <div
                  className="custom-wallpaper-upload-tile__bg"
                  style={uploadTileBg ? { backgroundImage: `url(${uploadTileBg})` } : { background: 'var(--card-bg)' }}
                  aria-hidden="true"
                />
                <div className="custom-wallpaper-upload-tile__overlay" aria-hidden="true" />
                <div className="w-full aspect-square flex items-center justify-center relative z-10">
                  <div className="custom-wallpaper-upload-tile__icon" aria-hidden="true">
                    <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                    </svg>
                  </div>
                </div>
              </label>
            )}

                {category.images && category.images.map((image, imgIdx) => {
                  const wallpaperId = `${category.name}-${imgIdx}`;
                  const imgPath = image.path;
                  const thumbUrlRaw = image.thumbPath || deriveThumbnail(imgPath);
                  const resolvedThumb = resolveRenderableUrl(thumbUrlRaw, image?.filePath);
                  const thumbUrl =
                    resolvedThumb ??
                    ((thumbUrlRaw && isAbsoluteFilePath(thumbUrlRaw)) ? null : thumbUrlRaw);

                  const stableTileKey = (() => {
                    const fp = image?.filePath;
                    if (fp && typeof fp === 'string') return `tile:${category.name}:fp:${fp}`;

                    const p = image?.path;
                    if (p && typeof p === 'string' && p.length < 240) return `tile:${category.name}:p:${p}`;

                    if (image?.kind && image?.config) {
                      const c = image.config || {};
                      const seed = (c.seed != null) ? String(c.seed) : '';
                      const cs = (c.colorStart != null) ? String(c.colorStart) : '';
                      const ce = (c.colorEnd != null) ? String(c.colorEnd) : '';
                      const ang = (c.angleDeg != null) ? String(c.angleDeg) : '';
                      return `tile:${category.name}:k:${image.kind}:seed:${seed}:a:${ang}:cs:${cs}:ce:${ce}`;
                    }

                    return `tile:${category.name}:idx:${imgIdx}`;
                  })();
                  const isGenerated = category.source === 'generated' || image?.kind === 'blobGradient' || image?.kind === 'gradient';
                  const hasFailed = !isGenerated && failedPaths.has(imgPath);
                  const isLoading = !isGenerated && selectedWallpaperId === wallpaperId && loadingWallpaper;
                  const isSelected = isGenerated
                    ? (image?.kind === 'gradient'
                        ? (
                          options?.backgroundType === 'gradient' &&
                          String(options?.customTheme?.colorStart || '').toLowerCase() === String(image?.config?.colorStart || '').toLowerCase() &&
                          String(options?.customTheme?.colorEnd || '').toLowerCase() === String(image?.config?.colorEnd || '').toLowerCase()
                        )
                        : (options?.backgroundType === 'blobGradient' && (options?.blobGradient?.seed === image?.config?.seed))
                      )
                    : isSelectedWallpaper(image);

                  const canDeleteCustom = isCustomCategory && !!image?.filePath && !!window?.tauriAPI?.deleteCustomBackground;

                  return (
                    <div
                      key={stableTileKey}
                      className={`wallpaper-card group relative cursor-pointer rounded-2xl overflow-hidden border aspect-square ${isSelected ? 'border-white/30' : hasFailed ? 'border-red-500' : isLoading ? 'border-yellow-500' : 'border-white/10 hover:border-white/20'}`}
                      onClick={() => {
                        if (isGenerated) {
                          if (image?.kind === 'gradient') {
                            applyGradient(image?.config || {});
                          } else {
                            applyBlobGradient(image?.config || {});
                          }
                          return;
                        }
                        const stablePath = image?.filePath || (isAbsoluteFilePath(imgPath) ? imgPath : null);
                        const selectionUrl = resolveRenderableUrl(imgPath, stablePath) || (typeof imgPath === 'string' ? imgPath : '');
                        selectWallpaper(selectionUrl, wallpaperId, category.source, stablePath);
                      }}
                      title={image.name}
                    >
                      {canDeleteCustom && (
                        <button
                          type="button"
                          className="absolute top-1 right-1 z-20 opacity-0 group-hover:opacity-100 focus:opacity-100 transition-opacity"
                          onClick={(e) => {
                            e.stopPropagation();
                            deleteCustomWallpaper(image);
                          }}
                          aria-label={t('deleteCustomBackground', { name: image.name })}
                          title={t('delete')}
                        >
                          <div className="w-6 h-6 flex items-center justify-center rounded-md bg-black/55 hover:bg-black/75">
                            <Trash2 className="w-3.5 h-3.5 text-white/85" />
                          </div>
                        </button>
                      )}

                      {isLoading && (
                        <div className="absolute inset-0 bg-black/40 backdrop-blur-[2px] flex items-center justify-center z-10">
                          <div className="w-5 h-5 border-2 border-t-transparent border-white rounded-full animate-spin"></div>
                        </div>
                      )}

                      {hasFailed && !isLoading && (
                        <div className="absolute inset-0 bg-black/40 flex items-center justify-center">
                          <span className="text-red-400 text-xs font-medium">{t('failed')}</span>
                        </div>
                      )}

                      <img
                        src={thumbUrl || 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=='}
                        alt={image.name}
                        loading="lazy"
                        decoding="async"
                        className="w-full aspect-square object-cover bg-[color:var(--card-bg)]"
                        onLoad={() => { if (hasFailed) setFailedPaths(prev => { const s = new Set(prev); s.delete(imgPath); return s; }); }}
                        onError={(e) => {
                          if (isGenerated) return;
                          // Only attempt the thumbs fallback for bundled /backgrounds assets.
                          if (image.path?.startsWith('/backgrounds/') && !e.target.src.includes('/thumbs/')) {
                            e.target.src = image.path.replace('/backgrounds/', '/backgrounds/thumbs/');
                            return;
                          }
                          if (!hasFailed) setFailedPaths(prev => new Set([...prev, imgPath]));
                          e.target.onerror = null;
                          e.target.src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==';
                          e.target.style.backgroundColor = '#444';
                        }}
                      />

                      <div className="absolute inset-0 opacity-0 hover:opacity-100 transition-opacity bg-gradient-to-t from-black/40 via-black/0 to-transparent" />
                    </div>
                  );
                })}
          </div>
        </div>
      </div>
    );
  };

  const sections = [];

  if (showWallpapers && customCategory) {
    sections.push({ key: `cat:${customCategory.name}`, node: renderCategoryCard(customCategory) });
  }

  if (showWallpapers) {
    sections.push({
      key: 'transparent',
      node: (
        <div className="sidebar-flat-section px-4 py-3">
          <div className="w-full flex items-center justify-between">
            <span className="text-xs text-gray-300">{t('transparentBackground')}</span>
            <label className="switch ml-4" style={{ transform: 'translateY(1px)' }}>
              <input
                type="checkbox"
                checked={options?.backgroundType === 'transparent'}
                onChange={() => {
                  setOptions((prev) => {
                    const isOn = prev?.backgroundType === 'transparent';
                    if (isOn) {
                      const restore = prev?.backgroundTypeBeforeTransparent || 'gradient';
                      const { backgroundTypeBeforeTransparent, ...rest } = prev || {};
                      return {
                        ...rest,
                        backgroundType: restore,
                      };
                    }

                    return {
                      ...(prev || {}),
                      backgroundTypeBeforeTransparent: prev?.backgroundType || 'gradient',
                      backgroundType: 'transparent',
                      wallpaper: null,
                      wallpaperSource: null,
                      wallpaperPath: null,
                    };
                  });
                }}
              />
              <span className="slider"></span>
            </label>
          </div>
        </div>
      )
    });
  }

  if (showWallpapers && otherCategories.length > 0) {
    for (const category of otherCategories) {
      sections.push({ key: `cat:${category.name}`, node: renderCategoryCard(category) });
    }
  }

  if (showEffects) {
    sections.push({
      key: 'effects',
      node: (
        <div className="sidebar-flat-section px-4 py-3">
          <div className="flex items-center gap-2 mb-3">
            <Sparkles className="w-4 h-4" />
            <span className="text-xs text-gray-300">{t('effects')}</span>
          </div>

          <div className="space-y-3">
            <div className="slider-field" style={{ marginBottom: 0 }}>
              <div className="slider-field__header">
                <span>{t('noise')}</span>
                <label className="switch ml-4" style={{ transform: 'translateY(1px)' }}>
                  <input
                    type="checkbox"
                    checked={!!options?.fx?.noise}
                    onChange={() => setOptions(prev => ({ ...prev, fx: { ...prev.fx, noise: !prev.fx?.noise } }))}
                  />
                  <span className="slider"></span>
                </label>
              </div>
            </div>
            <SliderField
              label={t('blur')}
              value={options?.fx?.blur || 0}
              min={0}
              max={30}
              step={1}
              formatValue={(val) => `${Math.round(val)}px`}
              onChange={(val) => setOptions(prev => ({ ...prev, fx: { ...prev.fx, blur: Math.round(val) } }))}
            />
            <SliderField
              label={t('brightness')}
              value={options?.fx?.brightness ?? 1}
              min={0.5}
              max={1.5}
              step={0.05}
              formatValue={(val) => `${Number(val).toFixed(2)}x`}
              onChange={(val) => setOptions(prev => ({ ...prev, fx: { ...prev.fx, brightness: Number(val.toFixed(2)) } }))}
            />
            <SliderField
              label={t('vignette')}
              value={options?.fx?.vignette ?? 0}
              min={0}
              max={1}
              step={0.05}
              formatValue={(val) => `${Math.round(val * 100)}%`}
              onChange={(val) => setOptions(prev => ({ ...prev, fx: { ...prev.fx, vignette: Number(val.toFixed(2)) } }))}
            />
            <div className="flex justify-end">
              <button
                type="button"
                onClick={() => setOptions(prev => ({ ...prev, fx: { noise: false, blur: 0, brightness: 1, vignette: 0 } }))}
                className="text-xs text-[color:var(--app-fg)] opacity-80 hover:opacity-90 flex items-center"
              >
                <span className="w-3 h-3 mr-1"><ResetIcon /></span>
                {t('reset')}
              </button>
            </div>
          </div>
        </div>
      )
    });
  }

  return (
    <div className="flex flex-col">
      {showWallpapers && failedPaths && failedPaths.size > 0 && (
        <button
          className="text-xs text-[color:var(--app-muted)] hover:text-[color:var(--app-fg)] w-full text-center underline py-1"
          onClick={retryFailedWallpapers}
        >
          {t('retryFailedWallpapers', { count: failedPaths.size })}
        </button>
      )}

      {sections.map((section, idx) => (
        <React.Fragment key={section.key}>
          {idx > 0 && <div className="sidebar-divider" />}
          {section.node}
        </React.Fragment>
      ))}
    </div>
  );
};

export default BackgroundsTab;